from __future__ import annotations

from ._serialize import canonical_string

type Node = tuple[object, tuple[int | str, ...], object, Node | None]
"""JSONPath tuple node `(value, location, root, parent)`.

Tuple nodes are a compact representation of transitive nodes created during JSONPath
evaluation. The only time you'd need to work with tuple nodes directly is when
implementing a function extension that accepts or returns values of type `NODES_TYPE`.
"""


class NodeList(list[Node]):
    """A list of tuple nodes."""

    def values(self) -> list[object]:
        """Return the values from this node list."""
        return [node[0] for node in self]

    def paths(self) -> list[str]:
        """Return a normalized paths for each node from this node list."""
        return [_path(node[1]) for node in self]

    def items(self) -> list[tuple[str, object]]:
        """Return a list of (path, value) pairs, one for each node in the list."""
        return [(_path(node[1]), node[0]) for node in self]

    def __str__(self) -> str:
        return f"NodeList{super().__str__()}"


class JSONPathNode:
    """A JSON-like value and its location in a JSON document.

    Parameters
    ----------
    node
        A tuple node generated by the JSONPath evaluator.

    Attributes
    ----------
    value : object
        The JSON-like value associated with this node.

        Assigning to `value` will update this node, and mutate source data, too.
        Mutating source data after evaluating a query can invalidate child nodes.
        Use at your own risk.
    location
        Property names and array indexes that make up the normalized path to `value`.
    """

    __slots__ = ("_parent", "_value", "location")

    def __init__(self, node: Node) -> None:
        self._value = node[0]
        self.location = node[1]
        self._parent = node[3]

    @property
    def value(self) -> object:
        """The JSON-like value at this node."""
        return self._value

    @value.setter
    def value(self, val: object) -> None:
        parent = self.parent()
        if parent is not None and self.location:
            # If data has changed since this node was created, this could fail.
            # Letting the exception raise is probably the most useful thing we can do.
            parent._value[self.location[-1]] = val  # type: ignore
        self._value = val

    def path(self) -> str:
        """Return the normalized path to this node in source data."""
        return _path(self.location)

    def parent(self) -> JSONPathNode | None:
        """Return this node's direct parent, or None if this is the document root."""
        return JSONPathNode(self._parent) if self._parent else None


class JSONPathNodeList(list[JSONPathNode]):
    """A list of JSONPath nodes with some helper methods."""

    def values(self) -> list[object]:
        """Return node values from this node list."""
        return [node.value for node in self]

    def paths(self) -> list[str]:
        """Return a normalized paths for each node in this node list."""
        return [node.path() for node in self]

    def items(self) -> list[tuple[str, object]]:
        """Return a list of (path, value) pairs, one for each node in the list."""
        return [(node.path(), node.value) for node in self]

    def __str__(self) -> str:
        return f"JSONPathNodeList{super().__str__()}"


def _path(location: tuple[str | int, ...]) -> str:
    it = iter(location)
    parts: list[str] = [str(next(it))]

    for p in it:
        if isinstance(p, str):
            if p.startswith("~"):
                parts.append(f"[~{canonical_string(p[1:])}]")
            else:
                parts.append(f"[{canonical_string(p)}]")
        else:
            parts.append(f"[{p}]")

    return "".join(parts)
